# Generated by Django 5.1.1 on 2024-09-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pythonmodel',
            name='code',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
