# Generated by Django 5.1.1 on 2024-09-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pythonmodel_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pythonmodel',
            name='output',
            field=models.TextField(null=True),
        ),
    ]
